[project]
name = "manim-post-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "rageout000@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "verifiers==0.2.0",
]

[project.scripts]
manim-post-train = "manim_post_train:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
